# Generated by Django 6.0.5 on 2026-05-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='department',
        ),
    ]
